### ISSUE TITLE
Support for clap_derive

### ISSUE THREAD

**Issue by MiSawa** [rust-cli/clap-verbosity-flag#27]
As [clap 3 includes derive](https://github.com/clap-rs/clap/tree/master/clap_derive), can `clap-verbosity-flag` also include `#[derive(Clap)]`-version of implementation, maybe with a feature flag or something?

**Comment by epage** [comment]
My plan is to switch over completely once clap3 is released.

**Comment by MiSawa** [comment]
> My plan is to switch over completely once clap3 is released.

Nice! Looking forward to it :)
