### ISSUE TITLE
Support for clap3?

### ISSUE THREAD

**Issue by SUPERCILEX** [rust-cli/clap-verbosity-flag#29]
Clap3 is now in the rc stage, so I'm looking to upgrade. Any idea when clap3 might be supported?

**Comment by epage** [comment]
I have a local branch with it ported to clap3.  I'm just waiting until I release 3.0.0 since I don't want to manage a lot of different pre-release crates.

**Comment by SUPERCILEX** [comment]
Congrats on the release!
