### ISSUE TITLE
Include usage in example

### ISSUE THREAD

**Issue by dimo414** [rust-cli/clap-verbosity-flag#31]
The current [example](https://github.com/rust-cli/clap-verbosity-flag/blob/70547a1f6d9e8689c653d4acdf6b5b611f72f46c/examples/example.rs) only shows adding a `verbose` field to the CLI struct, but doesn't demonstrate its usage. I imagine one could figure it out from the documentation, but it'd be nice if the example was more self-service.

**Comment by matthiasbeyer** [comment]
What do you mean with usage? How the resulting binary is called? Or how the `verbose` member is used in code?

**Comment by epage** [comment]
I noticed there were several areas we could improve, including
- Logger integration
- Further document the flags
- Document the flags in lib.rs, in addition to the readme

See https://github.com/rust-cli/clap-verbosity-flag/pull/32

**Comment by epage** [comment]
v0.4.1 is released with these improvements

**Comment by dimo414** [comment]
Thanks that's much clearer!
